// src/utils/templates.ts

export const TABLE_TEMPLATES = [
  {
    id: 'customers',
    name: 'Customers',
    icon: 'people-outline',
    category: 'Operations',
    description: 'Track your customer base',
    fields: [
      { name: 'Customer Name', type: 'text', isRequired: true },
      { name: 'Phone', type: 'text', isRequired: true },
      { name: 'Email', type: 'text', isRequired: false },
      { name: 'Address', type: 'text', isRequired: false },
      { name: 'City', type: 'text', isRequired: false },
      { name: 'Balance', type: 'currency', isRequired: false },
      { name: 'Status', type: 'select', isRequired: false, options: 'Active,Inactive' },
    ],
  },
  {
    id: 'sales_orders',
    name: 'Sales Orders',
    icon: 'document-text-outline',
    category: 'Finance',
    description: 'Manage your order book',
    fields: [
      { name: 'Order ID', type: 'text', isRequired: true },
      { name: 'Customer', type: 'link', isRequired: true },
      { name: 'Order Date', type: 'date', isRequired: true },
      { name: 'Delivery Date', type: 'date', isRequired: false },
      { name: 'Amount', type: 'currency', isRequired: true },
      { name: 'Status', type: 'select', isRequired: true, options: 'Confirmed,Pending,Processing,Cancelled,Delivered' },
    ],
  },
  {
    id: 'inventory',
    name: 'Inventory',
    icon: 'cube-outline',
    category: 'Inventory',
    description: 'Stock and product tracking',
    fields: [
      { name: 'Item Name', type: 'text', isRequired: true },
      { name: 'SKU', type: 'text', isRequired: false },
      { name: 'Category', type: 'select', isRequired: false, options: 'Raw Material,Finished Goods,Packaging,Other' },
      { name: 'Quantity', type: 'number', isRequired: true },
      { name: 'Reorder Level', type: 'number', isRequired: false },
      { name: 'Unit Price', type: 'currency', isRequired: false },
      { name: 'Location', type: 'text', isRequired: false },
    ],
  },
  {
    id: 'payments',
    name: 'Payments',
    icon: 'card-outline',
    category: 'Finance',
    description: 'Track receivables and payables',
    fields: [
      { name: 'Payment ID', type: 'text', isRequired: true },
      { name: 'Party', type: 'text', isRequired: true },
      { name: 'Date', type: 'date', isRequired: true },
      { name: 'Amount', type: 'currency', isRequired: true },
      { name: 'Mode', type: 'select', isRequired: false, options: 'Cash,UPI,NEFT,Cheque,RTGS' },
      { name: 'Type', type: 'select', isRequired: true, options: 'Received,Paid' },
      { name: 'Reference', type: 'text', isRequired: false },
    ],
  },
  {
    id: 'expenses',
    name: 'Expenses',
    icon: 'receipt-outline',
    category: 'Finance',
    description: 'Business expense tracking',
    fields: [
      { name: 'Date', type: 'date', isRequired: true },
      { name: 'Category', type: 'select', isRequired: true, options: 'Rent,Salary,Utilities,Transport,Raw Material,Marketing,Other' },
      { name: 'Description', type: 'text', isRequired: true },
      { name: 'Amount', type: 'currency', isRequired: true },
      { name: 'Paid By', type: 'text', isRequired: false },
      { name: 'Bill Ref', type: 'text', isRequired: false },
    ],
  },
];
